Ot168 23
alkemyTech/OT168-Java-server pull request #11
Opened 2022-03-19 02:18 UTC by Vortorexi2017

Subo los cambios de OT168-55 y OT168-23  en este caso PR de OT168-23
-Ambos tickets estan incompletos, pero debido a las relaciones entre sus entidades necesito cargar campos que dependen del otro.
-En ambos tickets no aplique excepciones ya que con estas branchs no puedo usar aún las customException y no quiero pisar las que ya creo Eliana.
Dejo evidencia en este caso en Organization que si desactivo la relación con Slides obtengo correctamente la respuesta:

Una vez mergeadas ambos tickets con main voy a subir los fixes para ambos tickets.

Evidencia Temporal:

GetAllOrganizationsById:
![GetAllOrganizationsById](https://user-images.githubusercontent.com/22580932/159102985-ada4b40e-c347-46e8-884a-7f7a91b3e7b9.png)

OrganizationEntity en DB creada temporalmente para testear:
![DBOrganizationEntity](https://user-images.githubusercontent.com/22580932/159102994-5cabc8a6-d23e-41b5-8ca6-fff0df626e76.png)

2022-03-19 14:57 UTC, paoliellolucas requested changes

2022-03-19 14:57 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/web/controllers/OrganizationController.java
> +@RequestMapping("/api/v1/organizations")
si el api/v1 lo definimos en el app.yaml lo podemos aprovechar en todos los endpoints!

2022-03-19 14:57 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/gateways/DefaultOrganizationGateway.java
> +        //TODO: orElseThrow  custom exception
respecto al orElseThrow ya tenemos la excepción ResourceNotFoundException mapeada al 404 en el global exception handler. Podes reusarla

2022-03-19 14:57 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/gateways/DefaultOrganizationGateway.java
> +    public static Organization organizationEntity2Organization(OrganizationEntity entity){
toModel, private y no static x lo q te comente en el otro perri

2022-03-19 18:52 UTC, Vortorexi2017 commented on src/main/java/com/alkemy/ong/data/gateways/DefaultOrganizationGateway.java
> +        //TODO: orElseThrow  custom exception
Si, la idea es usarla, pero desde esta branch aún no puedo acceder a ella por que se creo antes de que la rama de Eliana se mergeara, por eso lo voy a agregar junto al fix que voy a hacer de las relaciones de las entidades Organizacion y Slides.

2022-03-19 18:55 UTC, Vortorexi2017 commented on src/main/java/com/alkemy/ong/data/gateways/DefaultOrganizationGateway.java
> +    public static Organization organizationEntity2Organization(OrganizationEntity entity){
Fixed

2022-03-19 18:58 UTC, Vortorexi2017 commented on src/main/java/com/alkemy/ong/web/controllers/OrganizationController.java
> +@RequestMapping("/api/v1/organizations")
Eliminado api/v1 del controlller, dejo pendiente la parte del application.yaml para el fix.

2022-03-19 23:41 UTC, Vortorexi2017 commented on src/main/java/com/alkemy/ong/data/gateways/DefaultOrganizationGateway.java
> +        //TODO: orElseThrow  custom exception
Ahí me traje el main a esta rama y agregue la exception y quedo funcionando.

2022-03-22 02:23 UTC, paoliellolucas requested changes

2022-03-22 02:23 UTC, paoliellolucas commented on pom.xml
> +		<dependency>
En el pom de main ahora esta spring-boot-starter-validation q la incluye.
Tendríamos q borrar esta para q no quede duplicada

2022-03-22 02:23 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/gateways/DefaultOrganizationGateway.java
> +                                                .about_us_text(entity.getAboutUsText())
q raro con snake_case. Usemos camelCase en todos los casos.

2022-03-22 02:23 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/gateways/DefaultSlidesGateway.java
> +                .map(entity -> toModel(entity))
dentro de las lambdas se suele utilizar la primer letra de lo q se esta procesando. En este caso seria s de slide

2022-03-22 02:23 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/domain/slides/Slides.java
> +
muchas lineas en blanco innecesarias

2022-03-22 02:23 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/web/controllers/OrganizationController.java
> +    public static class OrganizationResponseDTO{
el response esta demás. OrganizationDto es suficiente. Si se usa solo acá, puede ser privada esta clase

2022-03-22 02:23 UTC, paoliellolucas commented on src/main/resources/schema.sql
> +    id_organization BIGINT unsigned NOT NULL
en ingles, el sufijo id va al final

2022-03-22 12:35 UTC, paoliellolucas approved these changes

2022-03-22 12:35 UTC, merged