1. Ticket OT168-42: Entpoint saveCategory
alkemyTech/OT168-Java-server pull request #17
Opened 2022-03-21 21:19 UTC by srsuarez05

1. Add the save method in the CategoryGateway interface.
2. Add the save method in the DefaultCategoryGateway class.
3. Add the save method in the CategoryService class.
4. Add the saveCategory endpoint to the CategoryController class.

2022-03-22 02:44 UTC, paoliellolucas requested changes

2022-03-22 02:44 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/gateways/DefaultCategoryGateway.java
> +		CategoryEntity newCategoryEntity = CategoryEntity.builder().id(category.getId()).name(category.getName())
es una pavada, pero te quedan re largas las lineas. 
Una buena practica cuando se usan builders, es poner un campo x linea, entonces es mucho mas claro al leer!

2022-03-22 02:54 UTC, srsuarez05 commented on src/main/java/com/alkemy/ong/data/gateways/DefaultCategoryGateway.java
> +		CategoryEntity newCategoryEntity = CategoryEntity.builder().id(category.getId()).name(category.getName())
Justamente lo tenia así, pero cuando le digo al IDE que me aplique el formato al código me junta todas las líneas, pero voy hacer ese cambio manual... Gracias Lucas!!

2022-03-22 18:17 UTC, paoliellolucas requested changes

2022-03-22 18:17 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/web/controllers/CategoryController.java
> +	private Boolean deleted = false;
en el dto no debería haber asignaciones

2022-03-22 19:21 UTC, srsuarez05 commented on src/main/java/com/alkemy/ong/web/controllers/CategoryController.java
> +	private Boolean deleted = false;
Cambio realizado.

2022-03-23 12:04 UTC, paoliellolucas approved these changes

2022-03-23 12:04 UTC, merged