ticket tested and working
alkemyTech/OT168-Java-server pull request #25
Opened 2022-03-23 17:50 UTC by Vortorexi2017

COMO usuario administrador
QUIERO actualizar los datos públicos de la Organización
PARA mantener la información actualizada

Criterios de aceptación:
Petición PUT hacia ruta /organization/public

Evidencia:
Organización previo al update:
![1-GetOrganization](https://user-images.githubusercontent.com/22580932/159763601-14134f17-1598-4ad1-9465-1e245dc2cafc.png)
Error 1: ID en path variable diferente al ID en body:
![2-DifferentId](https://user-images.githubusercontent.com/22580932/159763683-11bf0136-006c-4edc-8e8a-6556a18df1ef.png)
Error2: ID de una Organizacion que no existe:
![3-NoOrganizationExists](https://user-images.githubusercontent.com/22580932/159763796-650bf6d2-cdb3-45ca-8a51-e16dc9318a8d.png)
Request Correcto:
![4-validRequest](https://user-images.githubusercontent.com/22580932/159763857-aa268583-6e67-4a87-9a60-941a8eb3030a.png)
Verificacion con Get del Update:
![5-UpdatedOrganization](https://user-images.githubusercontent.com/22580932/159763902-1b85916a-e65d-487c-b95d-1d8e816c296d.png)

2022-03-23 19:19 UTC, paoliellolucas requested changes

2022-03-23 19:19 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/web/controllers/GlobalExceptionHandler.java
> +    protected ResponseEntity<Object> handleDifferentId(RuntimeException ex, WebRequest request) {
victor, en main ahora ya esta una nueva excepción q se encarga de lo mismo. 
Podes reutilizar esa? WebRequestException

2022-03-23 21:04 UTC, Vortorexi2017 commented on src/main/java/com/alkemy/ong/web/controllers/GlobalExceptionHandler.java
> +    protected ResponseEntity<Object> handleDifferentId(RuntimeException ex, WebRequest request) {
Listo borre la excepcion que habia creado y use la que ya estaba creada.

2022-03-24 12:46 UTC, paoliellolucas approved these changes

2022-03-24 12:46 UTC, merged