Feature/OT168-75
alkemyTech/OT168-Java-server pull request #37
Opened 2022-03-25 20:28 UTC by srsuarez05

Add Endpoint getAllComments

2022-03-25 23:12 UTC, paoliellolucas requested changes

2022-03-25 23:12 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/gateways/DefaultCommentGateway.java
> +		comments = commentRepository.findAll().stream().map(this::toModel).collect(toList());
no se esta garantizando el orden x fecha de creación. Hagamoslo x fecha descendiente para jugar un poco mas

2022-03-25 23:39 UTC, srsuarez05 commented on src/main/java/com/alkemy/ong/data/gateways/DefaultCommentGateway.java
> +		comments = commentRepository.findAll().stream().map(this::toModel).collect(toList());
Cambio realizado!!

2022-03-26 01:56 UTC, paoliellolucas approved these changes

2022-03-26 01:56 UTC, merged