Sergio suarez
alkemyTech/OT168-Java-server pull request #5
Opened 2022-03-17 22:19 UTC by srsuarez05

https://alkemy-labs.atlassian.net/browse/OT168-40

Endpoint Listado de Categorías

2022-03-18 13:47 UTC, paoliellolucas requested changes

2022-03-18 13:47 UTC, paoliellolucas commented on src/main/resources/data.sql
> +LOCK TABLES `alkemy_ong`.`categories` WRITE;
en este archivo dejemos limpitos los inserts. Saquemos los locks q no son necesarios para nuestro uso!

2022-03-18 13:47 UTC, paoliellolucas commented on src/main/resources/data.sql
> +VALUES ('Aventuras','Prueba Aventura',,NOW(),NOW(),0);
funciona este insert? Faltaria un valor

2022-03-18 13:47 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/web/controllers/category/CategoryController.java
> +package com.alkemy.ong.web.controllers.category;
en la capa web, como son detalles de implementación, no es necesario q definamos un paquetito para category. Q ademas va a tener solo esta clase. 
Déjalo directamente adentro de controllers donde van a estar todos

2022-03-18 13:47 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/web/controllers/category/dto/CategoryDTO.java
> +public class CategoryDTO {
x alguna razón hiciste los 2 dtos? el ticket lo pide?
Por otro lado, en lugar de tenerlo a parte, definilos como clase interna dentro del controller, ya que x lo pronto solo el controller lo usa.
Si en algún momento lo usa algun otro componente, recién ahi lo sacamos afuera del controller.

2022-03-18 13:47 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/web/controllers/category/dto/CategoryDTO.java
> +	public CategoryDTO(Long id, String name, String description, String image, LocalDateTime createdAt,
En lugar de inicializar los dto con el constructor, q son bastante error prone, usemos el builder de Lombok

2022-03-18 13:47 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/domain/category/CategoryService.java
> +		return categoryGateway.findAll();
Usemos de respuesta el ResponseEntity.ok para q retorne el 200 y en el body la lista de category dto.
Recordemos q a los controllers le llegan y retorna siempre dtos.

2022-03-18 13:47 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/domain/category/Category.java
> +	public Long getId() {
al definir los getters y setters de lombok, ya no tienen sentido estos getters y setters.
Usemos los de lombok

2022-03-18 13:47 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/domain/category/Category.java
> +	private Long id;
mal formateado.

2022-03-18 13:47 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/domain/category/Category.java
> +	public CategoryDTO fromThis() {
Los modelos vamos a usarlos solo como POJOs (plain-old java objects). 
Esto significa q no van a tener comportamiento. Solo getters y setters

2022-03-18 13:47 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/domain/category/Category.java
> +public class Category implements Serializable{
no es necesario q implemente de serializable ya q es solo usado dentro de la aplicación

2022-03-18 13:47 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/gateways/DefaultCategoryGateway.java
> +				.collect(Collectors.toList());
podemos usar static imports para leer:
.collect(toList()).
Es mas legible y ademas ya sabemos q es un collector ya q es parámetro del metodo collect.

2022-03-18 13:47 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/entities/CategoryEntity.java
> +	public static CategoryEntity from(Category category) {
las entities tmb las vamos a manejar como POJOs.
Por lo q no tiene q tener comportamiento. 
Este metodo tiene q estar en el defaultGateway.

2022-03-18 13:47 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/entities/CategoryEntity.java
> +	private LocalDateTime updateAt;
se tiene q llamar update"d"At. Asi queda coherente con el createdAt

2022-03-18 13:47 UTC, paoliellolucas commented on src/main/resources/schema.sql
> +  `updateAt` TIMESTAMP,
updatedAt

2022-03-18 23:34 UTC, srsuarez05 commented on src/main/resources/data.sql
> +LOCK TABLES `alkemy_ong`.`categories` WRITE;
Cambio realizado.

2022-03-18 23:35 UTC, srsuarez05 commented on src/main/resources/data.sql
> +VALUES ('Aventuras','Prueba Aventura',,NOW(),NOW(),0);
Cambio realizado.

2022-03-18 23:35 UTC, srsuarez05 commented on src/main/java/com/alkemy/ong/web/controllers/category/CategoryController.java
> +package com.alkemy.ong.web.controllers.category;
Cambio realizado.

2022-03-18 23:35 UTC, srsuarez05 commented on src/main/java/com/alkemy/ong/web/controllers/category/dto/CategoryDTO.java
> +public class CategoryDTO {
Cambio realizado.

2022-03-18 23:35 UTC, srsuarez05 commented on src/main/java/com/alkemy/ong/web/controllers/category/dto/CategoryDTO.java
> +	public CategoryDTO(Long id, String name, String description, String image, LocalDateTime createdAt,
Cambio realizado.

2022-03-18 23:35 UTC, srsuarez05 commented on src/main/java/com/alkemy/ong/domain/category/Category.java
> +public class Category implements Serializable{
Cambio realizado.

2022-03-18 23:35 UTC, srsuarez05 commented on src/main/java/com/alkemy/ong/data/gateways/DefaultCategoryGateway.java
> +				.collect(Collectors.toList());
Cambio realizado.

2022-03-18 23:35 UTC, srsuarez05 commented on src/main/java/com/alkemy/ong/data/entities/CategoryEntity.java
> +	public static CategoryEntity from(Category category) {
Cambio realizado.

2022-03-18 23:35 UTC, srsuarez05 commented on src/main/java/com/alkemy/ong/data/entities/CategoryEntity.java
> +	private LocalDateTime updateAt;
Cambio realizado.

2022-03-18 23:35 UTC, srsuarez05 commented on src/main/resources/schema.sql
> +  `updateAt` TIMESTAMP,
Cambio realizado.

2022-03-19 13:46 UTC, srsuarez05 commented on src/main/java/com/alkemy/ong/domain/category/Category.java
> +	private Long id;
Hola Lucas, no te entiendo cuando me mencionas que mal formateado

2022-03-19 13:46 UTC, srsuarez05 commented on src/main/java/com/alkemy/ong/domain/category/CategoryService.java
> +		return categoryGateway.findAll();
La implementación que me mencionas se realiza es en la clase Controller, allí se retorna el dto y la respuesta es un ResponseEntity.ok, en la clase service se maneja es el modelo Category... Quedo atento a tus indicaciones!!

2022-03-19 15:19 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/domain/category/CategoryService.java
> +		return categoryGateway.findAll();
mala mia!

2022-03-19 15:28 UTC, paoliellolucas approved these changes

2022-03-19 15:28 UTC, merged