AuthDocumentation OT168-89
alkemyTech/OT168-Java-server pull request #57
Opened 2022-04-02 16:59 UTC by AndreaReyna

2022-04-03 12:44 UTC, paoliellolucas requested changes

2022-04-03 12:44 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/web/controllers/AuthController.java
> +		@Schema(required = true, example = "passwordExample")
andre te pido un favor, podemos sacar el password de la respuesta? no esta bueno devolverla!

2022-04-03 12:44 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/web/controllers/AuthController.java
> +	})
te pido algo mas, me chequeas que cuando un usuario se registra por swagger, q dsp apreté el candadito de seguridad y pueda poner el token para hacer alguna otra acción? 
Se que hay q activarlo en la doc y no me acuerdo si ya se hizo! Podemos aprovechar este ticket para eso tmb!

2022-04-04 00:14 UTC, AndreaReyna commented on src/main/java/com/alkemy/ong/web/controllers/AuthController.java
> +	})
Listo Lucas, ahi lo agregue y subi las fotos a Jira. Saque algunas cosas que habia antes porque estaban hechas con SpringFox y no funcionaban

2022-04-04 17:42 UTC, merged