feature/OT168-32
alkemyTech/OT168-Java-server pull request #59
Opened 2022-04-03 00:29 UTC by srsuarez05

Add method delete user to UserController

2022-04-03 12:54 UTC, paoliellolucas requested changes

2022-04-03 12:54 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/entities/UserEntity.java
> +//@Builder
sin comments a menos q sean necesarios!

2022-04-04 03:35 UTC, srsuarez05 commented on src/main/java/com/alkemy/ong/data/entities/UserEntity.java
> +//@Builder
Siii, efectivamente se me fue por error ya que estaba doble :(

2022-04-04 17:48 UTC, paoliellolucas requested changes

2022-04-04 17:48 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/gateways/DefaultUserGateway.java
> +<<<<<<< HEAD
mm.. esto no debería estar!

2022-04-04 18:21 UTC, srsuarez05 commented on src/main/java/com/alkemy/ong/data/gateways/DefaultUserGateway.java
> +<<<<<<< HEAD
jeje no se como llego eso ahí... pero ya quedo solucionado el conflicto :)

2022-04-05 00:47 UTC, merged